# Ctrl+Backspace deletes previous word
map ctrl+backspace send_text all \x17

# Padding (why weird value? consistency with foot)
window_margin_width 4

# Make kitty transparent
background_opacity 0.8
